server:
  port: 8000
spring:
  application:
    name: worker-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas:
    - worker_service
    user: root
    password: 1234
    #url: jdbc:h2:mem:testdb
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
  #h2:
    #console:
      #enabled: true
      #path: /h2-console
