server:
  port: ${PORT:0}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  application:
    name: worker-service
  config:
    import:
    - optional:configserver:http://localhost:8888
  profiles:
    active: test
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/worker_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas:
    - worker_service
    user: root
    password: 1234

management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  show-actuator: true
  api-docs:
    path: worker-service/v3/api-docs
    #url: jdbc:h2:mem:testdb
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
  #h2:
    #console:
      #enabled: true
      #path: /h2-console
