server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: worker-service
        uri: lb://worker-service
        predicates:
        - Path=/workers/**
      - id: payroll-service
        uri: lb://payroll-service
        predicates:
        - Path=/payments/**