server:
  port: ${PORT:0}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  application:
    name: payroll-service
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
springdoc:
  show-actuator: true
  api-docs:
    path: payroll-service/v3/api-docs